language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install cython"
  - "pip install -r requirements.txt"
script:
    nosetests -w ./tests --with-coverage --cover-package="spyd,txENet,cube2map"

